import type { ParsedDocument } from './parser';
import type { Summary, ClauseAnalysis } from './schemas/ai';

export function generateMarkdownExport(
  doc: ParsedDocument,
  summary: Summary | null,
  analyses: ClauseAnalysis[] | null
): string {
  let md = `# Document Analysis: ${doc.filename || 'Untitled'}\n\n`;
  md += `*Generated by Lawesy on ${new Date().toLocaleDateString()}*\n\n`;

  if (summary) {
    md += `## 📋 Quick Summary\n\n`;
    md += `**TL;DR:** ${summary.oneLine}\n\n`;
    md += `### Key Points\n`;
    summary.keyPoints.forEach(p => md += `- ${p}\n`);
    md += `\n### Parties involved\n`;
    summary.parties.forEach(p => md += `- ${p}\n`);
    md += `\n`;
  }

  if (analyses && analyses.length > 0) {
    md += `## ⚖️ Key Clauses & Risks\n\n`;
    analyses.forEach(a => {
      md += `### ${a.title} (${a.clauseId})\n`;
      md += `**Risk Level:** ${a.risk.toUpperCase()}\n\n`;
      md += `**What it means:** ${a.plainSummary}\n\n`;
      
      if (a.riskReason) {
        md += `**Risk note:** ${a.riskReason}\n\n`;
      }
      
      if (a.obligations && a.obligations.length > 0) {
        md += `**Obligations:**\n`;
        a.obligations.forEach(o => md += `- ${o.action} (${o.who})\n`);
        md += `\n`;
      }
      
      if (a.deadlines && a.deadlines.length > 0) {
        md += `**Deadlines:**\n`;
        a.deadlines.forEach(d => md += `- ${d.description} ${d.date ? `(Date: ${d.date})` : d.relative ? `(Timeline: ${d.relative})` : ''}\n`);
        md += `\n`;
      }
      md += `---\n\n`;
    });
  }

  md += `## 📄 Original Text\n\n`;
  doc.sections.forEach(s => {
    if (s.heading) md += `### ${s.heading}\n\n`;
    s.clauses.forEach(c => {
      md += `${c.rawText}\n\n`;
    });
  });

  return md;
}

export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
