import type { Citation } from '../schemas/ai';
import { normalizeText } from '../parser';

/**
 * Strips zero-width characters and unusual control characters
 * that could be used for prompt smuggling.
 */
export function sanitizeText(text: string): string {
  // Remove zero-width chars and unprintable controls
  return text.replace(/[\u200B-\u200D\uFEFF]/g, '').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '');
}

/**
 * Very basic heuristic to detect obvious prompt injection attempts.
 * This is not foolproof, but adds a layer of defense.
 */
export function detectInjection(text: string): boolean {
  const lower = text.toLowerCase();
  const suspiciousPhrases = [
    'ignore previous instructions',
    'ignore all previous',
    'system prompt',
    'you are no longer',
    'roleplay as',
    'disregard previous',
    'print your initial',
    '[system]',
  ];

  return suspiciousPhrases.some(phrase => lower.includes(phrase));
}

/**
 * Verifies that the citations generated by the LLM actually exist in the original clause text.
 * Uses a basic sliding window / fuzzy match approach since LLMs sometimes slightly alter punctuation.
 */
export function verifyCitations(citations: Citation[], originalClauses: { id: string, text: string }[]): Citation[] {
  const validCitations: Citation[] = [];

  for (const citation of citations) {
    const originalClause = originalClauses.find(c => c.id === citation.clauseId);
    if (!originalClause) continue; // Invalid clause ID

    const normalizedOriginal = normalizeText(originalClause.text).toLowerCase();
    const normalizedQuote = normalizeText(citation.quote).toLowerCase();

    // If the quote is very short, it's risky to verify it loosely. We expect meaningful quotes.
    if (normalizedQuote.length < 10) continue; 

    // Check if the normalized quote appears in the normalized original text
    if (normalizedOriginal.includes(normalizedQuote)) {
      validCitations.push(citation);
    }
  }

  return validCitations;
}
